# Generated by Django 4.1 on 2022-08-29 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pavimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ss", models.TextField(max_length=255)),
                ("Os", models.TextField(max_length=255)),
                ("Data", models.DateTimeField(default=datetime.datetime.now)),
                ("Equipe", models.TextField(max_length=255)),
                ("Bairro", models.TextField(max_length=255)),
                ("Rua", models.TextField(max_length=255)),
                ("Referencia", models.TextField(max_length=255)),
                ("Servico", models.TextField(max_length=255)),
                ("Metragem", models.FloatField()),
                ("Pendente", models.BooleanField(default=False)),
            ],
        ),
    ]
