# Generated by Django 4.1.1 on 2023-03-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgoto',
            name='Bairro700',
        ),
        migrations.RemoveField(
            model_name='esgoto',
            name='Bairro900',
        ),
        migrations.RemoveField(
            model_name='esgoto',
            name='Equipe700',
        ),
        migrations.RemoveField(
            model_name='esgoto',
            name='Equipe900',
        ),
        migrations.RemoveField(
            model_name='pavimento',
            name='Bairro700',
        ),
        migrations.RemoveField(
            model_name='pavimento',
            name='Bairro900',
        ),
        migrations.RemoveField(
            model_name='pavimento',
            name='Equipe700',
        ),
        migrations.RemoveField(
            model_name='pavimento',
            name='Equipe900',
        ),
    ]
