# Generated by Django 4.1 on 2022-08-30 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pavimento",
            name="Observacoes",
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Data",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
