# Generated by Django 4.1.1 on 2023-02-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbase',
            name='Devolucao',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='materialbase',
            name='Observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialbase',
            name='Servico',
            field=models.CharField(choices=[('Operacional', 'Operacional'), ('Comercial', 'Comercial'), ('Unid. Tec', 'Unid. Tec')], max_length=255),
        ),
    ]
