# Generated by Django 4.1.7 on 2023-08-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='data'),
        ),
    ]
