# Generated by Django 4.1.1 on 2023-02-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0002_alter_materialbase_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbase',
            name='Observacao',
            field=models.CharField(blank=True, default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialbase',
            name='Servico',
            field=models.CharField(blank=True, choices=[('Operacional', 'Operacional'), ('Comercial', 'Comercial'), ('Unid. Tec', 'Unid. Tec')], max_length=255),
        ),
    ]
