# Generated by Django 4.1.1 on 2023-03-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0002_remove_esgoto_bairro700_remove_esgoto_bairro900_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbase',
            name='Localidade',
            field=models.CharField(choices=[('Salvador', 'Salvador'), ('Lauro', 'Lauro')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pavimento',
            name='Localidade',
            field=models.CharField(choices=[('Salvador', 'Salvador'), ('Lauro', 'Lauro')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pavimento',
            name='Medir',
            field=models.CharField(blank=True, choices=[('Medir', 'Medir'), ('Normal', 'Normal'), ('Prioridade', 'Prioridade')], max_length=255, null=True),
        ),
    ]
