# Generated by Django 4.1.1 on 2023-02-13 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0002_alter_materialbase_n_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lancamento',
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('materialbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='controle_pav.materialbase')),
            ],
            options={
                'verbose_name': 'Lancamento',
                'verbose_name_plural': 'Lançamentos',
            },
            bases=('controle_pav.materialbase',),
        ),
    ]
