# Generated by Django 4.1 on 2022-08-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0002_pavimento_observacoes_alter_pavimento_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="pavimento", name="Observacoes",),
    ]
