# Generated by Django 4.1 on 2022-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0003_remove_pavimento_observacoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pavimento",
            name="Observacao",
            field=models.TextField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
