# Generated by Django 4.1.5 on 2023-02-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0003_alter_materialbase_observacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgoto",
            name="Equipe",
            field=models.CharField(
                choices=[
                    ("11111", "11111"),
                    ("22222", "22222"),
                    ("33333", "33333"),
                    ("44444", "44444"),
                    ("55555", "55555"),
                    ("66666", "66666"),
                    ("77777", "77777"),
                    ("88888", "88888"),
                    ("99999", "99999"),
                    ("00000", "00000"),
                    ("127-A - GENILSON LIMA VITORIA", "127-A - GENILSON LIMA VITORIA"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="materialbase",
            name="Equipe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("11111", "11111"),
                    ("22222", "22222"),
                    ("33333", "33333"),
                    ("44444", "44444"),
                    ("55555", "55555"),
                    ("66666", "66666"),
                    ("77777", "77777"),
                    ("88888", "88888"),
                    ("99999", "99999"),
                    ("00000", "00000"),
                    ("127-A - GENILSON LIMA VITORIA", "127-A - GENILSON LIMA VITORIA"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Equipe",
            field=models.CharField(
                choices=[
                    ("11111", "11111"),
                    ("22222", "22222"),
                    ("33333", "33333"),
                    ("44444", "44444"),
                    ("55555", "55555"),
                    ("66666", "66666"),
                    ("77777", "77777"),
                    ("88888", "88888"),
                    ("99999", "99999"),
                    ("00000", "00000"),
                    ("127-A - GENILSON LIMA VITORIA", "127-A - GENILSON LIMA VITORIA"),
                ],
                max_length=255,
            ),
        ),
    ]
