# Generated by Django 4.1 on 2022-08-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0004_pavimento_observacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pavimento",
            name="Metragem",
            field=models.TextField(max_length=255),
        ),
    ]
