# Generated by Django 4.1.5 on 2023-02-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0004_alter_esgoto_equipe_alter_materialbase_equipe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialbase",
            name="quantidade_total",
            field=models.IntegerField(default=0),
        ),
    ]
