# Generated by Django 4.1 on 2022-09-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0005_alter_pavimento_metragem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pavimento", old_name="Pendente", new_name="Executado",
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Data",
            field=models.DateField(blank=True, null=True, verbose_name="data"),
        ),
    ]
