# Generated by Django 4.1.5 on 2023-02-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0005_materialbase_quantidade_total"),
    ]

    operations = [
        migrations.RemoveField(model_name="materialbase", name="quantidade_total",),
    ]
