# Generated by Django 4.1.5 on 2023-02-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0006_remove_materialbase_quantidade_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialbase",
            name="quantidade_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
