# Generated by Django 4.1 on 2022-09-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0006_rename_pendente_pavimento_executado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Esgoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ss", models.TextField(max_length=255)),
                ("OS", models.TextField(max_length=255)),
                ("Data", models.DateField(blank=True, null=True, verbose_name="data")),
                ("Equipe", models.TextField(max_length=255)),
                ("Bairro", models.TextField(max_length=255)),
                ("Rua", models.TextField(max_length=255)),
                ("Referencia", models.TextField(max_length=255)),
                ("Servico", models.TextField(max_length=255)),
                ("Observacao", models.TextField(max_length=255)),
                ("Executado", models.BooleanField(default=False)),
            ],
        ),
    ]
