# Generated by Django 4.1 on 2022-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0007_esgoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="pavimento",
            name="Prazo",
            field=models.BooleanField(default=False),
        ),
    ]
