# Generated by Django 4.1.5 on 2023-03-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0007_materialbase_quantidade_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materialbase",
            old_name="quantidade_total",
            new_name="Insumados",
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Bairro",
            field=models.CharField(
                choices=[
                    ("Ipitanga", "Ipitanga"),
                    ("Vilas Atlântico", "Vilas Atlântico"),
                    ("Caji", "Caji"),
                    ("Areia Branca", "Areia Branca"),
                    ("Portao", "Portão"),
                    ("Vila Praiana", "Vila Praiana"),
                    ("Aracui", "Aracui"),
                    ("Jockey Clube", "Jockey Clube"),
                    ("Pitangueiras", "Pitangueiras"),
                    ("Centro", "Centro"),
                    ("Buraquinho", "Buraquinho"),
                    ("Castanheiras", "Castanheiras"),
                    ("Itinga", "Itinga"),
                    ("São Cristóvão", "São Cristóvão"),
                    ("Cassange", "Cassange"),
                    ("Est do Coco", "Est do Coco"),
                    ("Jd Aeroporto", "Jd Aeroporto"),
                    ("Pa do Flamengo", "Pa do Flamengo"),
                    ("Jambeiro", "Jambeiro"),
                    ("Capelao SSA", "Capelão SSA"),
                    ("Lot Miragem", "Lot Miragem"),
                    ("Jd Margaridas", "Jd Margaridas"),
                    ("Itinga SSA", "Itinga SSA"),
                    ("Ipitanga SSA", "Ipitanga SSA"),
                    ("Areia Branc SSA", "Areia Branc SSA"),
                ],
                max_length=255,
            ),
        ),
    ]
