# Generated by Django 4.1.5 on 2023-03-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "controle_pav",
            "0008_rename_quantidade_total_materialbase_insumados_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgoto",
            name="Equipe",
            field=models.CharField(
                choices=[
                    ("106-A - JOSEILTON SANTOS", "106-A - JOSEILTON SANTOS"),
                    (
                        "111-A - VANILTON DA SILVA DE JESUS",
                        "111-A - VANILTON DA SILVA DE JESUS",
                    ),
                    (
                        "126-A - LUIZ ANTONIO SANTOS RAMOS",
                        "126-A - LUIZ ANTONIO SANTOS RAMOS",
                    ),
                    ("127-A - GENILSON LIMA VITORIA", "127-A - GENILSON LIMA VITORIA"),
                    (
                        "132A - MARCOS CASSIO DE JESUS SILVA",
                        "132A - MARCOS CASSIO DE JESUS SILVA",
                    ),
                    (
                        "144-A - EDILSON PETRONILIO DA SILVA",
                        "144-A - EDILSON PETRONILIO DA SILVA",
                    ),
                    (
                        "210A - JOSEILTON JESUS DOS SANTOS",
                        "210A - JOSEILTON JESUS DOS SANTOS",
                    ),
                    ("213A - SILVIO ALVES DA HORA", "213A - SILVIO ALVES DA HORA"),
                    (
                        "214-A - CRISTIANO VIANA MACEDO",
                        "214-A - CRISTIANO VIANA MACEDO",
                    ),
                    (
                        "215-A - NARCISO CONCEICAO FRANCA",
                        "215-A - NARCISO CONCEICAO FRANCA",
                    ),
                    (
                        "218A - JILTON RENILTON DE MELO",
                        "218A - JILTON RENILTON DE MELO",
                    ),
                    (
                        "221-A - EDCARLOS CARVALHO ALMEIDA",
                        "221-A - EDCARLOS CARVALHO ALMEIDA",
                    ),
                    (
                        "221-E - EDMILSON GOLVEIA ALMEIDA",
                        "221-E - EDMILSON GOLVEIA ALMEIDA",
                    ),
                    (
                        "222-A - EDVALDO RAIMUNDO DOS SANTOS",
                        "222-A - EDVALDO RAIMUNDO DOS SANTOS",
                    ),
                    (
                        "222E - GILVANDO DE SOUZA SANTOS",
                        "222E - GILVANDO DE SOUZA SANTOS",
                    ),
                    (
                        "308A - ADAILTON PASSOS DE SOUZA",
                        "308A - ADAILTON PASSOS DE SOUZA",
                    ),
                    ("309A - JOSE ROBERIO RODRIGUES", "309A - JOSE ROBERIO RODRIGUES"),
                    (
                        "310A - MARCOS JOSE CORREIA DOS SANTOS",
                        "310A - MARCOS JOSE CORREIA DOS SANTOS",
                    ),
                    (
                        "311-E - ADILTON JOSE DA SILVA SANTOS",
                        "311-E - ADILTON JOSE DA SILVA SANTOS",
                    ),
                    ("315-A - HANILTON SANTOS LOPES", "315-A - HANILTON SANTOS LOPES"),
                    ("320A - CELIO ROBERTO DE JESUS", "320A - CELIO ROBERTO DE JESUS"),
                    (
                        "402-E - CARLOS ALBERIO DOS SANTOS",
                        "402-E - CARLOS ALBERIO DOS SANTOS",
                    ),
                    ("405-E - MANOEL JOSE", "405-E - MANOEL JOSE"),
                    (
                        "409E - ULISSES ALVES DOS SANTOS FILHO",
                        "409E - ULISSES ALVES DOS SANTOS FILHO",
                    ),
                    ("410E - JOSE TELES FILHO", "410E - JOSE TELES FILHO"),
                    (
                        "422-E - REGINALDO FERREIRA SANTOS",
                        "422-E - REGINALDO FERREIRA SANTOS",
                    ),
                    (
                        "ASF700 - JOSEVAL NATIVIDADE DE JESUS",
                        "ASF700 - JOSEVAL NATIVIDADE DE JESUS",
                    ),
                    (
                        "CARLF - SERVICOS DE CARRO AGUA",
                        "CARLF - SERVICOS DE CARRO AGUA",
                    ),
                    ("ENC-07 - REGINALDO DA SILVA", "ENC-07 - REGINALDO DA SILVA"),
                    (
                        "PAV04A - VALDNEI VIEIRA DA CRUZ",
                        "PAV04A - VALDNEI VIEIRA DA CRUZ",
                    ),
                    (
                        "PAV09 - AILTON DE JESUS TEIXEIRA",
                        "PAV09 - AILTON DE JESUS TEIXEIRA",
                    ),
                    ("PG AG1 - PROGAGUA01", "PG AG1 - PROGAGUA01"),
                    ("PG ES1 - PROGESGOTO01", "PG ES1 - PROGESGOTO01"),
                    ("PVASF - PAVASFALTO", "PVASF - PAVASFALTO"),
                    (
                        "307-E - AILTON DOS SANTOS MACHADO",
                        "307-E - AILTON DOS SANTOS MACHADO",
                    ),
                    ("301-E - AMILTON BISPO DA CRUZ", "301-E - AMILTON BISPO DA CRUZ"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="materialbase",
            name="Equipe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("106-A - JOSEILTON SANTOS", "106-A - JOSEILTON SANTOS"),
                    (
                        "111-A - VANILTON DA SILVA DE JESUS",
                        "111-A - VANILTON DA SILVA DE JESUS",
                    ),
                    (
                        "126-A - LUIZ ANTONIO SANTOS RAMOS",
                        "126-A - LUIZ ANTONIO SANTOS RAMOS",
                    ),
                    ("127-A - GENILSON LIMA VITORIA", "127-A - GENILSON LIMA VITORIA"),
                    (
                        "132A - MARCOS CASSIO DE JESUS SILVA",
                        "132A - MARCOS CASSIO DE JESUS SILVA",
                    ),
                    (
                        "144-A - EDILSON PETRONILIO DA SILVA",
                        "144-A - EDILSON PETRONILIO DA SILVA",
                    ),
                    (
                        "210A - JOSEILTON JESUS DOS SANTOS",
                        "210A - JOSEILTON JESUS DOS SANTOS",
                    ),
                    ("213A - SILVIO ALVES DA HORA", "213A - SILVIO ALVES DA HORA"),
                    (
                        "214-A - CRISTIANO VIANA MACEDO",
                        "214-A - CRISTIANO VIANA MACEDO",
                    ),
                    (
                        "215-A - NARCISO CONCEICAO FRANCA",
                        "215-A - NARCISO CONCEICAO FRANCA",
                    ),
                    (
                        "218A - JILTON RENILTON DE MELO",
                        "218A - JILTON RENILTON DE MELO",
                    ),
                    (
                        "221-A - EDCARLOS CARVALHO ALMEIDA",
                        "221-A - EDCARLOS CARVALHO ALMEIDA",
                    ),
                    (
                        "221-E - EDMILSON GOLVEIA ALMEIDA",
                        "221-E - EDMILSON GOLVEIA ALMEIDA",
                    ),
                    (
                        "222-A - EDVALDO RAIMUNDO DOS SANTOS",
                        "222-A - EDVALDO RAIMUNDO DOS SANTOS",
                    ),
                    (
                        "222E - GILVANDO DE SOUZA SANTOS",
                        "222E - GILVANDO DE SOUZA SANTOS",
                    ),
                    (
                        "308A - ADAILTON PASSOS DE SOUZA",
                        "308A - ADAILTON PASSOS DE SOUZA",
                    ),
                    ("309A - JOSE ROBERIO RODRIGUES", "309A - JOSE ROBERIO RODRIGUES"),
                    (
                        "310A - MARCOS JOSE CORREIA DOS SANTOS",
                        "310A - MARCOS JOSE CORREIA DOS SANTOS",
                    ),
                    (
                        "311-E - ADILTON JOSE DA SILVA SANTOS",
                        "311-E - ADILTON JOSE DA SILVA SANTOS",
                    ),
                    ("315-A - HANILTON SANTOS LOPES", "315-A - HANILTON SANTOS LOPES"),
                    ("320A - CELIO ROBERTO DE JESUS", "320A - CELIO ROBERTO DE JESUS"),
                    (
                        "402-E - CARLOS ALBERIO DOS SANTOS",
                        "402-E - CARLOS ALBERIO DOS SANTOS",
                    ),
                    ("405-E - MANOEL JOSE", "405-E - MANOEL JOSE"),
                    (
                        "409E - ULISSES ALVES DOS SANTOS FILHO",
                        "409E - ULISSES ALVES DOS SANTOS FILHO",
                    ),
                    ("410E - JOSE TELES FILHO", "410E - JOSE TELES FILHO"),
                    (
                        "422-E - REGINALDO FERREIRA SANTOS",
                        "422-E - REGINALDO FERREIRA SANTOS",
                    ),
                    (
                        "ASF700 - JOSEVAL NATIVIDADE DE JESUS",
                        "ASF700 - JOSEVAL NATIVIDADE DE JESUS",
                    ),
                    (
                        "CARLF - SERVICOS DE CARRO AGUA",
                        "CARLF - SERVICOS DE CARRO AGUA",
                    ),
                    ("ENC-07 - REGINALDO DA SILVA", "ENC-07 - REGINALDO DA SILVA"),
                    (
                        "PAV04A - VALDNEI VIEIRA DA CRUZ",
                        "PAV04A - VALDNEI VIEIRA DA CRUZ",
                    ),
                    (
                        "PAV09 - AILTON DE JESUS TEIXEIRA",
                        "PAV09 - AILTON DE JESUS TEIXEIRA",
                    ),
                    ("PG AG1 - PROGAGUA01", "PG AG1 - PROGAGUA01"),
                    ("PG ES1 - PROGESGOTO01", "PG ES1 - PROGESGOTO01"),
                    ("PVASF - PAVASFALTO", "PVASF - PAVASFALTO"),
                    (
                        "307-E - AILTON DOS SANTOS MACHADO",
                        "307-E - AILTON DOS SANTOS MACHADO",
                    ),
                    ("301-E - AMILTON BISPO DA CRUZ", "301-E - AMILTON BISPO DA CRUZ"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Bairro",
            field=models.CharField(
                choices=[
                    ("5 - PORTAO", "5 - PORTAO"),
                    ("13 - ITINGA", "13 - ITINGA"),
                    ("10 - CENTRO", "10 - CENTRO"),
                    ("6 - VILA PRAIANA", "6 - VILA PRAIANA"),
                    ("1 - IPITANGA", "1 - IPITANGA"),
                    ("11 - BURAQUINHO", "11 - BURAQUINHO"),
                    ("17 - JD AEROPORTO", "17 - JD AEROPORTO"),
                    ("4 - AREIA BRANCA", "4 - AREIA BRANCA"),
                    ("38 - CAPELAO", "38 - CAPELAO"),
                    ("3 - CAJI", "3 - CAJI"),
                    ("35 - RECREI IPITANGA", "35 - RECREI IPITANGA"),
                    ("37 - VIDA NOVA", "37 - VIDA NOVA"),
                    ("2 - VILAS ATLANTICO", "2 - VILAS ATLANTICO"),
                    ("9 - PITANGUEIRAS", "9 - PITANGUEIRAS"),
                    ("23 - ITINGA SSA", "23 - ITINGA SSA"),
                    ("19 - JAMBEIRO", "19 - JAMBEIRO"),
                    ("36 - CAIXA DAGUA", "36 - CAIXA DAGUA"),
                    ("25 - AREIA BRAN SSA", "25 - AREIA BRAN SSA"),
                    ("39 - PQ SAO PAULO", "39 - PQ SAO PAULO"),
                    ("31 - QUINGOMA", "31 - QUINGOMA"),
                    ("20 - CAPELAO SSA", "20 - CAPELAO SSA"),
                    ("16 - EST DO COCO", "16 - EST DO COCO"),
                    ("33 - JD DOS PASSAROS", "33 - JD DOS PASSAROS"),
                    ("29 - JD CASTELAO", "29 - JD CASTELAO"),
                    ("34 - CIA MAR SSA", "34 - CIA MAR SSA"),
                    ("18 - PA DO FLAMENGO", "18 - PA DO FLAMENGO"),
                    ("24 - IPITANGA SSA", "24 - IPITANGA SSA"),
                    ("7 - ARACUI", "7 - ARACUI"),
                    ("28 - AEROPORTO", "28 - AEROPORTO"),
                    ("8 - JOCKEY CLUBE", "8 - JOCKEY CLUBE"),
                    ("27 - STELA MARIS SSA", "27 - STELA MARIS SSA"),
                    ("21 - LOT MIRAGEM", "21 - LOT MIRAGEM"),
                    ("15 - CASSANGE", "15 - CASSANGE"),
                    ("26 - CASSANGE SSA", "26 - CASSANGE SSA"),
                    ("14 - SAO CRISTOVAO", "14 - SAO CRISTOVAO"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Equipe",
            field=models.CharField(
                choices=[
                    ("106-A - JOSEILTON SANTOS", "106-A - JOSEILTON SANTOS"),
                    (
                        "111-A - VANILTON DA SILVA DE JESUS",
                        "111-A - VANILTON DA SILVA DE JESUS",
                    ),
                    (
                        "126-A - LUIZ ANTONIO SANTOS RAMOS",
                        "126-A - LUIZ ANTONIO SANTOS RAMOS",
                    ),
                    ("127-A - GENILSON LIMA VITORIA", "127-A - GENILSON LIMA VITORIA"),
                    (
                        "132A - MARCOS CASSIO DE JESUS SILVA",
                        "132A - MARCOS CASSIO DE JESUS SILVA",
                    ),
                    (
                        "144-A - EDILSON PETRONILIO DA SILVA",
                        "144-A - EDILSON PETRONILIO DA SILVA",
                    ),
                    (
                        "210A - JOSEILTON JESUS DOS SANTOS",
                        "210A - JOSEILTON JESUS DOS SANTOS",
                    ),
                    ("213A - SILVIO ALVES DA HORA", "213A - SILVIO ALVES DA HORA"),
                    (
                        "214-A - CRISTIANO VIANA MACEDO",
                        "214-A - CRISTIANO VIANA MACEDO",
                    ),
                    (
                        "215-A - NARCISO CONCEICAO FRANCA",
                        "215-A - NARCISO CONCEICAO FRANCA",
                    ),
                    (
                        "218A - JILTON RENILTON DE MELO",
                        "218A - JILTON RENILTON DE MELO",
                    ),
                    (
                        "221-A - EDCARLOS CARVALHO ALMEIDA",
                        "221-A - EDCARLOS CARVALHO ALMEIDA",
                    ),
                    (
                        "221-E - EDMILSON GOLVEIA ALMEIDA",
                        "221-E - EDMILSON GOLVEIA ALMEIDA",
                    ),
                    (
                        "222-A - EDVALDO RAIMUNDO DOS SANTOS",
                        "222-A - EDVALDO RAIMUNDO DOS SANTOS",
                    ),
                    (
                        "222E - GILVANDO DE SOUZA SANTOS",
                        "222E - GILVANDO DE SOUZA SANTOS",
                    ),
                    (
                        "308A - ADAILTON PASSOS DE SOUZA",
                        "308A - ADAILTON PASSOS DE SOUZA",
                    ),
                    ("309A - JOSE ROBERIO RODRIGUES", "309A - JOSE ROBERIO RODRIGUES"),
                    (
                        "310A - MARCOS JOSE CORREIA DOS SANTOS",
                        "310A - MARCOS JOSE CORREIA DOS SANTOS",
                    ),
                    (
                        "311-E - ADILTON JOSE DA SILVA SANTOS",
                        "311-E - ADILTON JOSE DA SILVA SANTOS",
                    ),
                    ("315-A - HANILTON SANTOS LOPES", "315-A - HANILTON SANTOS LOPES"),
                    ("320A - CELIO ROBERTO DE JESUS", "320A - CELIO ROBERTO DE JESUS"),
                    (
                        "402-E - CARLOS ALBERIO DOS SANTOS",
                        "402-E - CARLOS ALBERIO DOS SANTOS",
                    ),
                    ("405-E - MANOEL JOSE", "405-E - MANOEL JOSE"),
                    (
                        "409E - ULISSES ALVES DOS SANTOS FILHO",
                        "409E - ULISSES ALVES DOS SANTOS FILHO",
                    ),
                    ("410E - JOSE TELES FILHO", "410E - JOSE TELES FILHO"),
                    (
                        "422-E - REGINALDO FERREIRA SANTOS",
                        "422-E - REGINALDO FERREIRA SANTOS",
                    ),
                    (
                        "ASF700 - JOSEVAL NATIVIDADE DE JESUS",
                        "ASF700 - JOSEVAL NATIVIDADE DE JESUS",
                    ),
                    (
                        "CARLF - SERVICOS DE CARRO AGUA",
                        "CARLF - SERVICOS DE CARRO AGUA",
                    ),
                    ("ENC-07 - REGINALDO DA SILVA", "ENC-07 - REGINALDO DA SILVA"),
                    (
                        "PAV04A - VALDNEI VIEIRA DA CRUZ",
                        "PAV04A - VALDNEI VIEIRA DA CRUZ",
                    ),
                    (
                        "PAV09 - AILTON DE JESUS TEIXEIRA",
                        "PAV09 - AILTON DE JESUS TEIXEIRA",
                    ),
                    ("PG AG1 - PROGAGUA01", "PG AG1 - PROGAGUA01"),
                    ("PG ES1 - PROGESGOTO01", "PG ES1 - PROGESGOTO01"),
                    ("PVASF - PAVASFALTO", "PVASF - PAVASFALTO"),
                    (
                        "307-E - AILTON DOS SANTOS MACHADO",
                        "307-E - AILTON DOS SANTOS MACHADO",
                    ),
                    ("301-E - AMILTON BISPO DA CRUZ", "301-E - AMILTON BISPO DA CRUZ"),
                ],
                max_length=255,
            ),
        ),
    ]
