# Generated by Django 4.1.5 on 2023-03-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0009_alter_esgoto_equipe_alter_materialbase_equipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pavimento",
            name="Bairro",
            field=models.CharField(
                choices=[
                    ("1 - Ipitinga", "1 - Ipitinga"),
                    ("2 - Vilas Atlantico", "2 - Vilas Atlantico"),
                    ("3 - Caji", "3 - Caji"),
                    ("4 - Areia Branca", "4 - Areia Branca"),
                    ("5 - Portao", "5 - Portao"),
                    ("6 - Vila Praiana", "6 - Vila Praiana"),
                    ("7 - Aracui", "7 - Aracui"),
                    ("8 - Jockey Clube", "8 - Jockey Clube"),
                    ("9 - Pitangueiras", "9 - Pitangueiras"),
                    ("10 - Centro", "10 - Centro"),
                    ("11 - Buraquinho", "11 - Buraquinho"),
                    ("13 - Itinga", "13 - Itinga"),
                    ("14 - Sao Cristovao", "14 - Sao Cristovao"),
                    ("15 - Cassange", "15 - Cassange"),
                    ("16 - Est do Coco", "16 - Est do Coco"),
                    ("17 - Jd Aeroporto", "17 - Jd Aeroporto"),
                    ("18 - Pa do Flamengo", "18 - Pa do Flamengo"),
                    ("19 - Jambeiro", "19 - Jambeiro"),
                    ("20 - Capelao SSA", "20 - Capelao SSA"),
                    ("21 - Lote Miragem", "21 - Lote Miragem"),
                    ("23 - Itinga SSA", "23 - Itinga SSA"),
                    ("24 - Ipitinga SSA", "24 - Ipitinga SSA"),
                    ("25 - Areia Branca SSA", "25 - Areia Branca SSA"),
                    ("26 - Cassange SSA", "26 - Cassange SSA"),
                    ("27 - Stella Maris SSA", "27 - Stella Maris SSA"),
                    ("28 - Aeroporto", "28 - Aeroporto"),
                    ("29 - Jd Castelao", "29 - Jd Castelao"),
                    ("31 - Quingoma", "31 - Quingoma"),
                    ("33 - Jd dos Passaros", "33 - Jd dos Passaros"),
                    ("34 - Cia Mar SSA", "34 - Cia Mar SSA"),
                    ("35 - Recrei Ipitinga", "35 - Recrei Ipitinga"),
                    ("36 - Caixa Dagua", "36 - Caixa Dagua"),
                    ("37 - Vida Nova", "37 - Vida Nova"),
                    ("38 - Capelao", "38 - Capelao"),
                    ("39 - Pq Sao Paulo", "39 - Pq Sao Paulo"),
                ],
                max_length=255,
            ),
        ),
    ]
