# Generated by Django 4.1 on 2022-09-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0009_pendencias"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendencias",
            name="Ss",
            field=models.TextField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
