# Generated by Django 4.1.1 on 2022-09-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0010_pendencias_ss'),
    ]

    operations = [
        migrations.AddField(
            model_name='pavimento',
            name='Met_Final',
            field=models.TextField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='pavimento',
            name='Ss_Final',
            field=models.TextField(default=' ', max_length=255),
        ),
    ]
