# Generated by Django 4.1.5 on 2023-03-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0011_alter_esgoto_bairro_alter_materialbase_equipe_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pavimento", old_name="Bairro", new_name="Bairro700",
        ),
        migrations.AddField(
            model_name="pavimento",
            name="Bairro900",
            field=models.CharField(
                blank=True,
                choices=[
                    ("13 - Rio Vermelho", "13 - Rio Vermelho"),
                    ("14 - Amaralina", "14 - Amaralina"),
                    ("15 - Pituba", "15 - Pituba"),
                    ("16 - Boca do Rio", "16 - Boca do Rio"),
                    ("17 - Piata", "17 - Piata"),
                    ("18 - Itapua", "18 - Itapua"),
                    ("22 - Jd Margaridas", "22 - Jd Margaridas"),
                    ("29 - Pernambues", "29 - Pernambues"),
                    ("50 - CAB", "50 - CAB"),
                    ("52 - Cam das Arvores", "52 - Cam das Arvores"),
                    ("53 - Itaigara", "53 - Itaigara"),
                    ("54 - Stiep", "54 - Stiep"),
                    ("64 - Sao Cristovao", "64 - Sao Cristovao"),
                    ("105 - Nordt Amaralina", "105 - Nordt Amaralina"),
                    ("113 - Patamares", "113 - Patamares"),
                    ("115 - Imbui", "115 - Imbui"),
                    ("116 - Costa Azul", "116 - Costa Azul"),
                    ("117 - Stella Maris", "117 - Stella Maris"),
                    ("118 - Jardim Armacao", "118 - Jardim Armacao"),
                    ("119 - Mussurunga", "119 - Mussurunga"),
                    ("139 - Trobogy", "139 - Trobogy"),
                    ("140 - Paralela", "140 - Paralela"),
                    ("141 - PituaÃ§u", "141 - PituaÃ§u"),
                    ("145 - Alt Coqueirinho", "145 - Alt Coqueirinho"),
                    ("149 - Aeroporto", "149 - Aeroporto"),
                    ("183 - Narandiba", "183 - Narandiba"),
                    ("186 - Pa do Flamengo", "186 - Pa do Flamengo"),
                    ("191 - Bairro da Paz", "191 - Bairro da Paz"),
                    ("193 - N Brasilia Itap", "193 - N Brasilia Itap"),
                    ("204 - Faz Grande IV", "204 - Faz Grande IV"),
                    ("233 - Cassange", "233 - Cassange"),
                    ("238 - Itinga", "238 - Itinga"),
                    ("242 - Mussurunga", "242 - Mussurunga"),
                    ("243 - Sao Cristovao", "243 - Sao Cristovao"),
                    ("246 - Cassange", "246 - Cassange"),
                    ("301 - Areia Branca", "301 - Areia Branca"),
                    ("304 - Saboeiro", "304 - Saboeiro"),
                    ("305 - Sao Rafael", "305 - Sao Rafael"),
                    ("306 - Vale dos Lagos", "306 - Vale dos Lagos"),
                    ("307 - Canabrava", "307 - Canabrava"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Equipe",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
