# Generated by Django 4.1 on 2022-09-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "controle_pav",
            "0012_alter_esgoto_executado_alter_esgoto_observacao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pendencias",
            name="Executado",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
