# Generated by Django 4.1 on 2022-09-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0013_pendencias_executado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgoto",
            name="Executado",
            field=models.BooleanField(
                choices=[(True, "Executado"), (False, "Pendente")]
            ),
        ),
        migrations.AlterField(
            model_name="esgoto",
            name="Servico",
            field=models.TextField(
                choices=[
                    ("Vedacao", "Vedacao"),
                    ("Consertos", "Consertos"),
                    ("Desobstrucao", "Desobstrucao"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Executado",
            field=models.BooleanField(
                choices=[(True, "Executado"), (False, "Pendente")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Servico",
            field=models.TextField(
                choices=[
                    ("Asfalto", "Asfalto"),
                    ("Concreto", "Concreto"),
                    ("Blocos", "Blocos"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pendencias",
            name="Executado",
            field=models.BooleanField(
                choices=[(True, "Executado"), (False, "Pendente")]
            ),
        ),
    ]
