# Generated by Django 3.2.11 on 2022-10-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0014_alter_esgoto_executado_alter_esgoto_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgoto',
            name='OS',
        ),
        migrations.RemoveField(
            model_name='pavimento',
            name='Os',
        ),
        migrations.AlterField(
            model_name='esgoto',
            name='Equipe',
            field=models.TextField(choices=[('Eq307E-Ailton', 'Eq307E-Ailton'), ('Eq222E-Gilvando', 'Eq222E-Gilvando'), ('Eq227E-Carlos', 'Eq227E-Carlos'), ('EqEsgoto-Esgoto', 'EqEsgoto-Esgoto'), ('EqMoto-Motoqueiro', 'EqMoto-Motoqueiro'), ('EqAgua-Vazamento', 'EqAgua-Vazamento')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pavimento',
            name='Equipe',
            field=models.TextField(choices=[('Eq213-Silvio', 'Eq213-Silvio'), ('Eq221-Edcarlos', 'Eq221-Edcarlos'), ('Eq214-Cristiano', 'Eq214-Cristiano'), ('Eq218A-Jilton', 'Eq218A-Jilton'), ('Eq309A-Roberio', 'Eq309A-Roberio'), ('Eq224A-Haroldo', 'Eq224A-Haroldo'), ('Eq215A-Narciso', 'Eq215A-Narciso'), ('Eq320A-Celio', 'Eq320A-Celio'), ('Eq315A-Hanilton', 'Eq315A-Hanilton'), ('Eq218A-Jilton', 'Eq218A-Jilton'), ('Eq308A-Adailton', 'Eq308A-Adailton'), ('EqEsgoto-Esgoto', 'EqEsgoto-Esgoto'), ('EqMoto-Motoqueiro', 'EqMoto-Motoqueiro')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pavimento',
            name='Metragem',
            field=models.TextField(max_length=255),
        ),
    ]
