# Generated by Django 4.1.5 on 2023-03-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0014_remove_esgoto_bairro_remove_esgoto_equipe_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="materialbase", name="Equipe",),
        migrations.AddField(
            model_name="materialbase",
            name="Equipe700",
            field=models.CharField(
                blank=True,
                choices=[
                    ("106-A - JOSEILTON SANTOS", "106-A - JOSEILTON SANTOS"),
                    (
                        "111-A - VANILTON DA SILVA DE JESUS",
                        "111-A - VANILTON DA SILVA DE JESUS",
                    ),
                    (
                        "126-A - LUIZ ANTONIO SANTOS RAMOS",
                        "126-A - LUIZ ANTONIO SANTOS RAMOS",
                    ),
                    ("127-A - GENILSON LIMA VITORIA", "127-A - GENILSON LIMA VITORIA"),
                    (
                        "132A - MARCOS CASSIO DE JESUS SILVA",
                        "132A - MARCOS CASSIO DE JESUS SILVA",
                    ),
                    (
                        "144-A - EDILSON PETRONILIO DA SILVA",
                        "144-A - EDILSON PETRONILIO DA SILVA",
                    ),
                    (
                        "210A - JOSEILTON JESUS DOS SANTOS",
                        "210A - JOSEILTON JESUS DOS SANTOS",
                    ),
                    ("213A - SILVIO ALVES DA HORA", "213A - SILVIO ALVES DA HORA"),
                    (
                        "214-A - CRISTIANO VIANA MACEDO",
                        "214-A - CRISTIANO VIANA MACEDO",
                    ),
                    (
                        "215-A - NARCISO CONCEICAO FRANCA",
                        "215-A - NARCISO CONCEICAO FRANCA",
                    ),
                    (
                        "218A - JILTON RENILTON DE MELO",
                        "218A - JILTON RENILTON DE MELO",
                    ),
                    (
                        "221-A - EDCARLOS CARVALHO ALMEIDA",
                        "221-A - EDCARLOS CARVALHO ALMEIDA",
                    ),
                    (
                        "221-E - EDMILSON GOLVEIA ALMEIDA",
                        "221-E - EDMILSON GOLVEIA ALMEIDA",
                    ),
                    (
                        "222-A - EDVALDO RAIMUNDO DOS SANTOS",
                        "222-A - EDVALDO RAIMUNDO DOS SANTOS",
                    ),
                    (
                        "222E - GILVANDO DE SOUZA SANTOS",
                        "222E - GILVANDO DE SOUZA SANTOS",
                    ),
                    (
                        "308A - ADAILTON PASSOS DE SOUZA",
                        "308A - ADAILTON PASSOS DE SOUZA",
                    ),
                    ("309A - JOSE ROBERIO RODRIGUES", "309A - JOSE ROBERIO RODRIGUES"),
                    (
                        "310A - MARCOS JOSE CORREIA DOS SANTOS",
                        "310A - MARCOS JOSE CORREIA DOS SANTOS",
                    ),
                    (
                        "311-E - ADILTON JOSE DA SILVA SANTOS",
                        "311-E - ADILTON JOSE DA SILVA SANTOS",
                    ),
                    ("315-A - HANILTON SANTOS LOPES", "315-A - HANILTON SANTOS LOPES"),
                    ("320A - CELIO ROBERTO DE JESUS", "320A - CELIO ROBERTO DE JESUS"),
                    (
                        "402-E - CARLOS ALBERIO DOS SANTOS",
                        "402-E - CARLOS ALBERIO DOS SANTOS",
                    ),
                    ("405-E - MANOEL JOSE", "405-E - MANOEL JOSE"),
                    (
                        "409E - ULISSES ALVES DOS SANTOS FILHO",
                        "409E - ULISSES ALVES DOS SANTOS FILHO",
                    ),
                    ("410E - JOSE TELES FILHO", "410E - JOSE TELES FILHO"),
                    (
                        "422-E - REGINALDO FERREIRA SANTOS",
                        "422-E - REGINALDO FERREIRA SANTOS",
                    ),
                    (
                        "ASF700 - JOSEVAL NATIVIDADE DE JESUS",
                        "ASF700 - JOSEVAL NATIVIDADE DE JESUS",
                    ),
                    (
                        "CARLF - SERVICOS DE CARRO AGUA",
                        "CARLF - SERVICOS DE CARRO AGUA",
                    ),
                    ("ENC-07 - REGINALDO DA SILVA", "ENC-07 - REGINALDO DA SILVA"),
                    (
                        "PAV04A - VALDNEI VIEIRA DA CRUZ",
                        "PAV04A - VALDNEI VIEIRA DA CRUZ",
                    ),
                    (
                        "PAV09 - AILTON DE JESUS TEIXEIRA",
                        "PAV09 - AILTON DE JESUS TEIXEIRA",
                    ),
                    ("PG AG1 - PROGAGUA01", "PG AG1 - PROGAGUA01"),
                    ("PG ES1 - PROGESGOTO01", "PG ES1 - PROGESGOTO01"),
                    ("PVASF - PAVASFALTO", "PVASF - PAVASFALTO"),
                    (
                        "307-E - AILTON DOS SANTOS MACHADO",
                        "307-E - AILTON DOS SANTOS MACHADO",
                    ),
                    ("301-E - AMILTON BISPO DA CRUZ", "301-E - AMILTON BISPO DA CRUZ"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="materialbase",
            name="Equipe900",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "117A - MARCIO DE FREITAS ARAUJO",
                        "117A - MARCIO DE FREITAS ARAUJO",
                    ),
                    ("138-A - WENDELL COSTA SANTOS", "138-A - WENDELL COSTA SANTOS"),
                    (
                        "139-A - LEANDRO SOUZA DE ALMEIDA",
                        "139-A - LEANDRO SOUZA DE ALMEIDA",
                    ),
                    (
                        "140-A - JONATAS SOUSA CONCEICAO",
                        "140-A - JONATAS SOUSA CONCEICAO",
                    ),
                    (
                        "141-A - MOISES LEANDRO DE F ARAUJO",
                        "141-A - MOISES LEANDRO DE F ARAUJO",
                    ),
                    (
                        "142-A - LOURIVAL NERI ANDRADE NETO",
                        "142-A - LOURIVAL NERI ANDRADE NETO",
                    ),
                    (
                        "143-A - YAN QUARESMA DOS SANTOS",
                        "143-A - YAN QUARESMA DOS SANTOS",
                    ),
                    (
                        "148-A - JEFERSON DOS SANTOS RODRIGUES",
                        "148-A - JEFERSON DOS SANTOS RODRIGUES",
                    ),
                    (
                        "149-A - CARLOS FELIPE SANTANA FERNADE",
                        "149-A - CARLOS FELIPE SANTANA FERNADE",
                    ),
                    (
                        "150-A - ANDRE LUIZ CHAVES DOS SANTOS",
                        "150-A - ANDRE LUIZ CHAVES DOS SANTOS",
                    ),
                    (
                        "201-E - ARLINDO TIAGO DE JESUS",
                        "201-E - ARLINDO TIAGO DE JESUS",
                    ),
                    (
                        "202-E - ADRIANO PAULINO DE OLIVEIRA",
                        "202-E - ADRIANO PAULINO DE OLIVEIRA",
                    ),
                    ("204-A - ELIOSMAR JOSE SANTOS", "204-A - ELIOSMAR JOSE SANTOS"),
                    ("209-A - WENDEL FELIX", "209-A - WENDEL FELIX"),
                    (
                        "216-A - ARIVALDO SOUZA MONTEIRO",
                        "216-A - ARIVALDO SOUZA MONTEIRO",
                    ),
                    ("216GC - EDISON SAMUEL", "216GC - EDISON SAMUEL"),
                    ("217A - VIANEI MOREIRA CARDORA", "217A - VIANEI MOREIRA CARDORA"),
                    (
                        "218 E - REINALDO BISPO ALCANTARA",
                        "218 E - REINALDO BISPO ALCANTARA",
                    ),
                    (
                        "220-E - MARCIO NEI DA CONCEICAO SOUSA",
                        "220-E - MARCIO NEI DA CONCEICAO SOUSA",
                    ),
                    ("224-E - GILVANDRO DIAS", "224-E - GILVANDRO DIAS"),
                    (
                        "225-A - EDLON DOS SANTOS GUEDES",
                        "225-A - EDLON DOS SANTOS GUEDES",
                    ),
                    (
                        "227E - CARLOS RUBIRA SOUZA SANTOS",
                        "227E - CARLOS RUBIRA SOUZA SANTOS",
                    ),
                    (
                        "228-A - IVAN HONORATO DOS SANTOS",
                        "228-A - IVAN HONORATO DOS SANTOS",
                    ),
                    (
                        "302-A - AURELITO ALVES CONCEICAO",
                        "302-A - AURELITO ALVES CONCEICAO",
                    ),
                    (
                        "303-E - GILSON MENEZES DOS SANTOS",
                        "303-E - GILSON MENEZES DOS SANTOS",
                    ),
                    (
                        "304-A - EDVALDO JOSE P DOS SANTOS",
                        "304-A - EDVALDO JOSE P DOS SANTOS",
                    ),
                    (
                        "304-E - MARCELO VIEIRA DE ARAUJO",
                        "304-E - MARCELO VIEIRA DE ARAUJO",
                    ),
                    (
                        "305-A - HUGO DE SANTANA COUTINHO",
                        "305-A - HUGO DE SANTANA COUTINHO",
                    ),
                    (
                        "306-A - PAULO SERGIO BISPO PEREIRA",
                        "306-A - PAULO SERGIO BISPO PEREIRA",
                    ),
                    ("309E - JOSE MOREIRA OLIVEIRA", "309E - JOSE MOREIRA OLIVEIRA"),
                    ("312A - ADRIANO DE JESUS ROCHA", "312A - ADRIANO DE JESUS ROCHA"),
                    (
                        "313A - JOSE CARLOS DE ANUNCIACAO",
                        "313A - JOSE CARLOS DE ANUNCIACAO",
                    ),
                    (
                        "316-A - JAMACI SANTANA DA SILVA",
                        "316-A - JAMACI SANTANA DA SILVA",
                    ),
                    ("321 E - JORGE DA SILVA SANTOS", "321 E - JORGE DA SILVA SANTOS"),
                    (
                        "322A - CARLOS WILLIAN MAIA DACE",
                        "322A - CARLOS WILLIAN MAIA DACE",
                    ),
                    ("323-A - AILTON DA SILVA", "323-A - AILTON DA SILVA"),
                    ("324-A - MARCONI SANTOS CAITO", "324-A - MARCONI SANTOS CAITO"),
                    (
                        "401-E - SIDNEY QUARESMA DOS SANTOS",
                        "401-E - SIDNEY QUARESMA DOS SANTOS",
                    ),
                    (
                        "403-E - EZEQUIAS ANTONIO DOS SANTOS",
                        "403-E - EZEQUIAS ANTONIO DOS SANTOS",
                    ),
                    (
                        "404-E - FABIO DOS SANTOS DE JESUS",
                        "404-E - FABIO DOS SANTOS DE JESUS",
                    ),
                    (
                        "416-E - TIAGO ANTONIO DOS SANTOS SOUZA",
                        "416-E - TIAGO ANTONIO DOS SANTOS SOUZA",
                    ),
                    (
                        "422-E - ANTONIO MARCOS S BRITO",
                        "422-E - ANTONIO MARCOS S BRITO",
                    ),
                    (
                        "426-E - MAURICIO JOAQUIM DO NASCIMENTO",
                        "426-E - MAURICIO JOAQUIM DO NASCIMENTO",
                    ),
                    ("430E - CHARLES MARINHO", "430E - CHARLES MARINHO"),
                    (
                        "511GC - FLAVIANO BORGES DE ACCACIO",
                        "511GC - FLAVIANO BORGES DE ACCACIO",
                    ),
                    (
                        "512 - PAOLO THADEU SANTOS E DA SILVA",
                        "512 - PAOLO THADEU SANTOS E DA SILVA",
                    ),
                    (
                        "513PF - NIVALDO GONCALVES DA CONCEICAO",
                        "513PF - NIVALDO GONCALVES DA CONCEICAO",
                    ),
                    (
                        "516PC - CARMILTON GOMES GONCALVES",
                        "516PC - CARMILTON GOMES GONCALVES",
                    ),
                    (
                        "ASF900 - JOSEVAL NATIVIDADE DE JESUS",
                        "ASF900 - JOSEVAL NATIVIDADE DE JESUS",
                    ),
                    (
                        "CARSSA - SERVICOS DE CARRO AGUA",
                        "CARSSA - SERVICOS DE CARRO AGUA",
                    ),
                    (
                        "CMB02A - JAQUESON CONCEICAO DOS SANTOS",
                        "CMB02A - JAQUESON CONCEICAO DOS SANTOS",
                    ),
                    (
                        "CMB03A - DAILTON DA HORA DE CASTRO AP",
                        "CMB03A - DAILTON DA HORA DE CASTRO AP",
                    ),
                    (
                        "CMB04A - PAULO ANDERSON BONFIM DOS SANT",
                        "CMB04A - PAULO ANDERSON BONFIM DOS SANT",
                    ),
                    ("EQ146A - ELIELSON", "EQ146A - ELIELSON"),
                ],
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="materialbase",
            name="EquipeGestor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("106-A - JOSEILTON SANTOS", "106-A - JOSEILTON SANTOS"),
                    (
                        "111-A - VANILTON DA SILVA DE JESUS",
                        "111-A - VANILTON DA SILVA DE JESUS",
                    ),
                    (
                        "126-A - LUIZ ANTONIO SANTOS RAMOS",
                        "126-A - LUIZ ANTONIO SANTOS RAMOS",
                    ),
                    ("127-A - GENILSON LIMA VITORIA", "127-A - GENILSON LIMA VITORIA"),
                    (
                        "132A - MARCOS CASSIO DE JESUS SILVA",
                        "132A - MARCOS CASSIO DE JESUS SILVA",
                    ),
                    (
                        "144-A - EDILSON PETRONILIO DA SILVA",
                        "144-A - EDILSON PETRONILIO DA SILVA",
                    ),
                    (
                        "210A - JOSEILTON JESUS DOS SANTOS",
                        "210A - JOSEILTON JESUS DOS SANTOS",
                    ),
                    ("213A - SILVIO ALVES DA HORA", "213A - SILVIO ALVES DA HORA"),
                    (
                        "214-A - CRISTIANO VIANA MACEDO",
                        "214-A - CRISTIANO VIANA MACEDO",
                    ),
                    (
                        "215-A - NARCISO CONCEICAO FRANCA",
                        "215-A - NARCISO CONCEICAO FRANCA",
                    ),
                    (
                        "218A - JILTON RENILTON DE MELO",
                        "218A - JILTON RENILTON DE MELO",
                    ),
                    (
                        "221-A - EDCARLOS CARVALHO ALMEIDA",
                        "221-A - EDCARLOS CARVALHO ALMEIDA",
                    ),
                    (
                        "221-E - EDMILSON GOLVEIA ALMEIDA",
                        "221-E - EDMILSON GOLVEIA ALMEIDA",
                    ),
                    (
                        "222-A - EDVALDO RAIMUNDO DOS SANTOS",
                        "222-A - EDVALDO RAIMUNDO DOS SANTOS",
                    ),
                    (
                        "222E - GILVANDO DE SOUZA SANTOS",
                        "222E - GILVANDO DE SOUZA SANTOS",
                    ),
                    (
                        "308A - ADAILTON PASSOS DE SOUZA",
                        "308A - ADAILTON PASSOS DE SOUZA",
                    ),
                    ("309A - JOSE ROBERIO RODRIGUES", "309A - JOSE ROBERIO RODRIGUES"),
                    (
                        "310A - MARCOS JOSE CORREIA DOS SANTOS",
                        "310A - MARCOS JOSE CORREIA DOS SANTOS",
                    ),
                    (
                        "311-E - ADILTON JOSE DA SILVA SANTOS",
                        "311-E - ADILTON JOSE DA SILVA SANTOS",
                    ),
                    ("315-A - HANILTON SANTOS LOPES", "315-A - HANILTON SANTOS LOPES"),
                    ("320A - CELIO ROBERTO DE JESUS", "320A - CELIO ROBERTO DE JESUS"),
                    (
                        "402-E - CARLOS ALBERIO DOS SANTOS",
                        "402-E - CARLOS ALBERIO DOS SANTOS",
                    ),
                    ("405-E - MANOEL JOSE", "405-E - MANOEL JOSE"),
                    (
                        "409E - ULISSES ALVES DOS SANTOS FILHO",
                        "409E - ULISSES ALVES DOS SANTOS FILHO",
                    ),
                    ("410E - JOSE TELES FILHO", "410E - JOSE TELES FILHO"),
                    (
                        "422-E - REGINALDO FERREIRA SANTOS",
                        "422-E - REGINALDO FERREIRA SANTOS",
                    ),
                    (
                        "ASF700 - JOSEVAL NATIVIDADE DE JESUS",
                        "ASF700 - JOSEVAL NATIVIDADE DE JESUS",
                    ),
                    (
                        "CARLF - SERVICOS DE CARRO AGUA",
                        "CARLF - SERVICOS DE CARRO AGUA",
                    ),
                    ("ENC-07 - REGINALDO DA SILVA", "ENC-07 - REGINALDO DA SILVA"),
                    (
                        "PAV04A - VALDNEI VIEIRA DA CRUZ",
                        "PAV04A - VALDNEI VIEIRA DA CRUZ",
                    ),
                    (
                        "PAV09 - AILTON DE JESUS TEIXEIRA",
                        "PAV09 - AILTON DE JESUS TEIXEIRA",
                    ),
                    ("PG AG1 - PROGAGUA01", "PG AG1 - PROGAGUA01"),
                    ("PG ES1 - PROGESGOTO01", "PG ES1 - PROGESGOTO01"),
                    ("PVASF - PAVASFALTO", "PVASF - PAVASFALTO"),
                    (
                        "307-E - AILTON DOS SANTOS MACHADO",
                        "307-E - AILTON DOS SANTOS MACHADO",
                    ),
                    ("301-E - AMILTON BISPO DA CRUZ", "301-E - AMILTON BISPO DA CRUZ"),
                    (
                        "117A - MARCIO DE FREITAS ARAUJO",
                        "117A - MARCIO DE FREITAS ARAUJO",
                    ),
                    ("138-A - WENDELL COSTA SANTOS", "138-A - WENDELL COSTA SANTOS"),
                    (
                        "139-A - LEANDRO SOUZA DE ALMEIDA",
                        "139-A - LEANDRO SOUZA DE ALMEIDA",
                    ),
                    (
                        "140-A - JONATAS SOUSA CONCEICAO",
                        "140-A - JONATAS SOUSA CONCEICAO",
                    ),
                    (
                        "141-A - MOISES LEANDRO DE F ARAUJO",
                        "141-A - MOISES LEANDRO DE F ARAUJO",
                    ),
                    (
                        "142-A - LOURIVAL NERI ANDRADE NETO",
                        "142-A - LOURIVAL NERI ANDRADE NETO",
                    ),
                    (
                        "143-A - YAN QUARESMA DOS SANTOS",
                        "143-A - YAN QUARESMA DOS SANTOS",
                    ),
                    (
                        "148-A - JEFERSON DOS SANTOS RODRIGUES",
                        "148-A - JEFERSON DOS SANTOS RODRIGUES",
                    ),
                    (
                        "149-A - CARLOS FELIPE SANTANA FERNADE",
                        "149-A - CARLOS FELIPE SANTANA FERNADE",
                    ),
                    (
                        "150-A - ANDRE LUIZ CHAVES DOS SANTOS",
                        "150-A - ANDRE LUIZ CHAVES DOS SANTOS",
                    ),
                    (
                        "201-E - ARLINDO TIAGO DE JESUS",
                        "201-E - ARLINDO TIAGO DE JESUS",
                    ),
                    (
                        "202-E - ADRIANO PAULINO DE OLIVEIRA",
                        "202-E - ADRIANO PAULINO DE OLIVEIRA",
                    ),
                    ("204-A - ELIOSMAR JOSE SANTOS", "204-A - ELIOSMAR JOSE SANTOS"),
                    ("209-A - WENDEL FELIX", "209-A - WENDEL FELIX"),
                    (
                        "216-A - ARIVALDO SOUZA MONTEIRO",
                        "216-A - ARIVALDO SOUZA MONTEIRO",
                    ),
                    ("216GC - EDISON SAMUEL", "216GC - EDISON SAMUEL"),
                    ("217A - VIANEI MOREIRA CARDORA", "217A - VIANEI MOREIRA CARDORA"),
                    (
                        "218 E - REINALDO BISPO ALCANTARA",
                        "218 E - REINALDO BISPO ALCANTARA",
                    ),
                    (
                        "220-E - MARCIO NEI DA CONCEICAO SOUSA",
                        "220-E - MARCIO NEI DA CONCEICAO SOUSA",
                    ),
                    ("224-E - GILVANDRO DIAS", "224-E - GILVANDRO DIAS"),
                    (
                        "225-A - EDLON DOS SANTOS GUEDES",
                        "225-A - EDLON DOS SANTOS GUEDES",
                    ),
                    (
                        "227E - CARLOS RUBIRA SOUZA SANTOS",
                        "227E - CARLOS RUBIRA SOUZA SANTOS",
                    ),
                    (
                        "228-A - IVAN HONORATO DOS SANTOS",
                        "228-A - IVAN HONORATO DOS SANTOS",
                    ),
                    (
                        "302-A - AURELITO ALVES CONCEICAO",
                        "302-A - AURELITO ALVES CONCEICAO",
                    ),
                    (
                        "303-E - GILSON MENEZES DOS SANTOS",
                        "303-E - GILSON MENEZES DOS SANTOS",
                    ),
                    (
                        "304-A - EDVALDO JOSE P DOS SANTOS",
                        "304-A - EDVALDO JOSE P DOS SANTOS",
                    ),
                    (
                        "304-E - MARCELO VIEIRA DE ARAUJO",
                        "304-E - MARCELO VIEIRA DE ARAUJO",
                    ),
                    (
                        "305-A - HUGO DE SANTANA COUTINHO",
                        "305-A - HUGO DE SANTANA COUTINHO",
                    ),
                    (
                        "306-A - PAULO SERGIO BISPO PEREIRA",
                        "306-A - PAULO SERGIO BISPO PEREIRA",
                    ),
                    ("309E - JOSE MOREIRA OLIVEIRA", "309E - JOSE MOREIRA OLIVEIRA"),
                    ("312A - ADRIANO DE JESUS ROCHA", "312A - ADRIANO DE JESUS ROCHA"),
                    (
                        "313A - JOSE CARLOS DE ANUNCIACAO",
                        "313A - JOSE CARLOS DE ANUNCIACAO",
                    ),
                    (
                        "316-A - JAMACI SANTANA DA SILVA",
                        "316-A - JAMACI SANTANA DA SILVA",
                    ),
                    ("321 E - JORGE DA SILVA SANTOS", "321 E - JORGE DA SILVA SANTOS"),
                    (
                        "322A - CARLOS WILLIAN MAIA DACE",
                        "322A - CARLOS WILLIAN MAIA DACE",
                    ),
                    ("323-A - AILTON DA SILVA", "323-A - AILTON DA SILVA"),
                    ("324-A - MARCONI SANTOS CAITO", "324-A - MARCONI SANTOS CAITO"),
                    (
                        "401-E - SIDNEY QUARESMA DOS SANTOS",
                        "401-E - SIDNEY QUARESMA DOS SANTOS",
                    ),
                    (
                        "403-E - EZEQUIAS ANTONIO DOS SANTOS",
                        "403-E - EZEQUIAS ANTONIO DOS SANTOS",
                    ),
                    (
                        "404-E - FABIO DOS SANTOS DE JESUS",
                        "404-E - FABIO DOS SANTOS DE JESUS",
                    ),
                    (
                        "416-E - TIAGO ANTONIO DOS SANTOS SOUZA",
                        "416-E - TIAGO ANTONIO DOS SANTOS SOUZA",
                    ),
                    (
                        "422-E - ANTONIO MARCOS S BRITO",
                        "422-E - ANTONIO MARCOS S BRITO",
                    ),
                    (
                        "426-E - MAURICIO JOAQUIM DO NASCIMENTO",
                        "426-E - MAURICIO JOAQUIM DO NASCIMENTO",
                    ),
                    ("430E - CHARLES MARINHO", "430E - CHARLES MARINHO"),
                    (
                        "511GC - FLAVIANO BORGES DE ACCACIO",
                        "511GC - FLAVIANO BORGES DE ACCACIO",
                    ),
                    (
                        "512 - PAOLO THADEU SANTOS E DA SILVA",
                        "512 - PAOLO THADEU SANTOS E DA SILVA",
                    ),
                    (
                        "513PF - NIVALDO GONCALVES DA CONCEICAO",
                        "513PF - NIVALDO GONCALVES DA CONCEICAO",
                    ),
                    (
                        "516PC - CARMILTON GOMES GONCALVES",
                        "516PC - CARMILTON GOMES GONCALVES",
                    ),
                    (
                        "ASF900 - JOSEVAL NATIVIDADE DE JESUS",
                        "ASF900 - JOSEVAL NATIVIDADE DE JESUS",
                    ),
                    (
                        "CARSSA - SERVICOS DE CARRO AGUA",
                        "CARSSA - SERVICOS DE CARRO AGUA",
                    ),
                    (
                        "CMB02A - JAQUESON CONCEICAO DOS SANTOS",
                        "CMB02A - JAQUESON CONCEICAO DOS SANTOS",
                    ),
                    (
                        "CMB03A - DAILTON DA HORA DE CASTRO AP",
                        "CMB03A - DAILTON DA HORA DE CASTRO AP",
                    ),
                    (
                        "CMB04A - PAULO ANDERSON BONFIM DOS SANT",
                        "CMB04A - PAULO ANDERSON BONFIM DOS SANT",
                    ),
                    ("EQ146A - ELIELSON", "EQ146A - ELIELSON"),
                ],
                max_length=255,
            ),
        ),
    ]
