# Generated by Django 3.2.11 on 2022-10-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0015_auto_20221005_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='esgoto',
            name='Localidade',
            field=models.TextField(choices=[('Salvador', 'Salvador'), ('Lauro', 'Lauro')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='esgoto',
            name='Medir',
            field=models.TextField(blank=True, choices=[('Medir', 'Medir'), ('Normal', 'Normal'), ('Prioridade', 'Prioridade')], null=True),
        ),
        migrations.AddField(
            model_name='pavimento',
            name='Localidade',
            field=models.TextField(choices=[('Salvador', 'Salvador'), ('Lauro', 'Lauro')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pavimento',
            name='Medir',
            field=models.TextField(blank=True, choices=[('Medir', 'Medir'), ('Normal', 'Normal'), ('Prioridade', 'Prioridade')], null=True),
        ),
        migrations.AddField(
            model_name='pendencias',
            name='Localidade',
            field=models.TextField(choices=[('Salvador', 'Salvador'), ('Lauro', 'Lauro')], default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendencias',
            name='Medir',
            field=models.TextField(blank=True, choices=[('Medir', 'Medir'), ('Normal', 'Normal'), ('Prioridade', 'Prioridade')], null=True),
        ),
    ]
