# Generated by Django 4.1.5 on 2023-03-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0017_remove_materialbase_equipe_materialbase_equipegestor"),
        (
            "controle_pav",
            "0017_remove_materialbase_equipe_materialbase_equipegestor_and_more",
        ),
    ]

    operations = []
