# Generated by Django 3.2.7 on 2022-11-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0018_alter_pavimento_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavimento',
            name='Equipe',
            field=models.TextField(choices=[('equipes', 'Eq 127A - Luiz'), ('equipes', '\nEq 320A - Celio'), ('equipes', '\nEq 213A - Silvio'), ('equipes', '\nEquipe5'), ('equipes', '\nEquipe6'), ('equipes', '\nEquipe7'), ('equipes', '\nEquipe8'), ('equipes', '\nEquipe9')], max_length=255),
        ),
    ]
