# Generated by Django 4.1.1 on 2022-11-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0019_alter_pavimento_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavimento',
            name='Ss',
            field=models.IntegerField(max_length=20),
        ),
    ]
