# Generated by Django 4.1.5 on 2023-01-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0020_alter_pavimento_ss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgoto", name="Bairro", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="esgoto",
            name="Equipe",
            field=models.CharField(
                choices=[
                    ("Eq307E-Ailton", "Eq307E-Ailton"),
                    ("Eq222E-Gilvando", "Eq222E-Gilvando"),
                    ("Eq227E-Carlos", "Eq227E-Carlos"),
                    ("EqEsgoto-Esgoto", "EqEsgoto-Esgoto"),
                    ("EqMoto-Motoqueiro", "EqMoto-Motoqueiro"),
                    ("EqAgua-Vazamento", "EqAgua-Vazamento"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="esgoto",
            name="Observacao",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="esgoto",
            name="Referencia",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="esgoto", name="Rua", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Bairro",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Equipe",
            field=models.CharField(
                choices=[("equipes", "teste100"), ("equipes", "teste200")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Met_Final",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Metragem",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Observacao",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Referencia",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pavimento", name="Rua", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Servico",
            field=models.CharField(
                choices=[
                    ("Asfalto", "Asfalto"),
                    ("Concreto", "Concreto"),
                    ("Blocos", "Blocos"),
                ],
                max_length=255,
                verbose_name="Serviço",
            ),
        ),
        migrations.AlterField(
            model_name="pavimento", name="Ss", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Ss_Final",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="pendencias", name="Ss", field=models.IntegerField(),
        ),
    ]
