# Generated by Django 4.1.5 on 2023-01-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0023_alter_esgoto_ss_alter_pavimento_ss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgoto", name="Ss", field=models.CharField(max_length=9),
        ),
    ]
