# Generated by Django 4.1.5 on 2023-01-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0025_alter_pendencias_detalhes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgoto", name="Ss", field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name="pavimento", name="Ss", field=models.IntegerField(max_length=9),
        ),
    ]
