# Generated by Django 4.1.5 on 2023-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0026_alter_esgoto_ss_alter_pavimento_ss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgoto", name="Ss", field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="pavimento", name="Ss", field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name="pendencias", name="Ss", field=models.CharField(max_length=9),
        ),
    ]
