# Generated by Django 4.1.5 on 2023-01-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0027_alter_esgoto_ss_alter_pavimento_ss_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgoto",
            name="Equipe",
            field=models.CharField(
                choices=[
                    ("equipes", "teste100"),
                    ("equipes", "teste202"),
                    ("equipes", "teste203"),
                    ("equipes", "teste204"),
                    ("equipes", "teste205"),
                    ("equipes", "teste206"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Equipe",
            field=models.CharField(
                choices=[
                    ("equipes", "teste100"),
                    ("equipes", "teste202"),
                    ("equipes", "teste203"),
                    ("equipes", "teste204"),
                    ("equipes", "teste205"),
                    ("equipes", "teste206"),
                ],
                max_length=255,
            ),
        ),
    ]
