# Generated by Django 4.1.5 on 2023-01-27 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("controle_pav", "0028_alter_esgoto_equipe_alter_pavimento_equipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="pavimento",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
