# Generated by Django 4.1.5 on 2023-01-27 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0029_pavimento_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pavimento", old_name="created_by", new_name="Criador",
        ),
    ]
