# Generated by Django 4.1.1 on 2023-01-28 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0030_rename_created_by_pavimento_criador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pavimento',
            old_name='Criador',
            new_name='created_by',
        ),
    ]
