# Generated by Django 4.1.1 on 2023-01-28 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle_pav', '0033_pavimento_deleted_by_pavimento_last_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pavimento',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='pavimento',
            name='last_deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
