# Generated by Django 4.1.1 on 2023-01-29 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0036_pendencias_created_by_pendencias_last_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esgoto',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='esgoto',
            name='last_deleted_by',
        ),
        migrations.RemoveField(
            model_name='esgoto',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='pavimento',
            name='last_deleted_by',
        ),
        migrations.RemoveField(
            model_name='pendencias',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pendencias',
            name='last_deleted_by',
        ),
        migrations.RemoveField(
            model_name='pendencias',
            name='last_edited_by',
        ),
    ]
