# Generated by Django 4.1.5 on 2023-01-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0038_esgoto_created_by_esgoto_last_edited_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pavimento",
            name="Executado",
            field=models.BooleanField(
                choices=[(True, "Executado"), (False, "Pendente")],
                db_index=True,
                default=False,
            ),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Localidade",
            field=models.TextField(
                choices=[("Salvador", "Salvador"), ("Lauro", "Lauro")],
                db_index=True,
                max_length=255,
            ),
        ),
    ]
