# Generated by Django 4.1.1 on 2023-02-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0039_alter_pavimento_executado_alter_pavimento_localidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esgoto',
            name='Bairro',
            field=models.CharField(choices=[('ipitanga', 'Ipitanga'), ('vilasatlantico', 'Vilas Atlântico'), ('caji', 'Caji'), ('areiabranca', 'Areia Branca'), ('portao', 'Portão'), ('vilapraiana', 'Vila Praiana'), ('aracui', 'Aracui'), ('jockeyclube', 'Jockey Clube'), ('pitangueiras', 'Pitangueiras'), ('centro', 'Centro'), ('buraquinho', 'Buraquinho'), ('castanheiras', 'Castanheiras'), ('itinga', 'Itinga'), ('saocristovao', 'São Cristóvão'), ('cassange', 'Cassange'), ('estdococo', 'Est do Coco'), ('jdaeroporto', 'Jd Aeroporto'), ('padoflamengo', 'Pa do Flamengo'), ('jambeiro', 'Jambeiro'), ('capelaaossa', 'Capelaão SSA'), ('lotmiragem', 'Lot Miragem'), ('jdmargaridas', 'Jd Margaridas'), ('itingassa', 'Itinga SSA'), ('ipitangassa', 'Ipitanga SSA'), ('areiabranc_ssa', 'Areia Branc SSA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pavimento',
            name='Bairro',
            field=models.CharField(choices=[('ipitanga', 'Ipitanga'), ('vilasatlantico', 'Vilas Atlântico'), ('caji', 'Caji'), ('areiabranca', 'Areia Branca'), ('portao', 'Portão'), ('vilapraiana', 'Vila Praiana'), ('aracui', 'Aracui'), ('jockeyclube', 'Jockey Clube'), ('pitangueiras', 'Pitangueiras'), ('centro', 'Centro'), ('buraquinho', 'Buraquinho'), ('castanheiras', 'Castanheiras'), ('itinga', 'Itinga'), ('saocristovao', 'São Cristóvão'), ('cassange', 'Cassange'), ('estdococo', 'Est do Coco'), ('jdaeroporto', 'Jd Aeroporto'), ('padoflamengo', 'Pa do Flamengo'), ('jambeiro', 'Jambeiro'), ('capelaaossa', 'Capelaão SSA'), ('lotmiragem', 'Lot Miragem'), ('jdmargaridas', 'Jd Margaridas'), ('itingassa', 'Itinga SSA'), ('ipitangassa', 'Ipitanga SSA'), ('areiabranc_ssa', 'Areia Branc SSA')], max_length=255),
        ),
    ]
