# Generated by Django 4.1.1 on 2023-02-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0040_alter_esgoto_bairro_alter_pavimento_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pavimento',
            name='Bairro',
            field=models.CharField(choices=[('ipitanga', 'Ipitanga'), ('vilas_atlantico', 'Vilas Atlântico'), ('caji', 'Caji'), ('areia_branca', 'Areia Branca'), ('portao', 'Portão'), ('vila_praiana', 'Vila Praiana'), ('aracui', 'Aracui'), ('jockey_clube', 'Jockey Clube'), ('pitangueiras', 'Pitangueiras'), ('centro', 'Centro'), ('buraquinho', 'Buraquinho'), ('castanheiras', 'Castanheiras'), ('itinga', 'Itinga'), ('sao_cristovao', 'São Cristóvão'), ('cassange', 'Cassange'), ('estdococo', 'Est do Coco'), ('jd_aeroporto', 'Jd Aeroporto'), ('pa_do_flamengo', 'Pa do Flamengo'), ('jambeiro', 'Jambeiro'), ('capelaao_ssa', 'Capelaão SSA'), ('lot_miragem', 'Lot Miragem'), ('jd_margaridas', 'Jd Margaridas'), ('itinga_ssa', 'Itinga SSA'), ('ipitanga_ssa', 'Ipitanga SSA'), ('areia_branc_ssa', 'Areia Branc SSA')], max_length=255),
        ),
    ]
