# Generated by Django 4.1.5 on 2023-02-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle_pav", "0044_alter_esgoto_bairro_alter_pavimento_bairro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esgoto",
            name="Equipe",
            field=models.CharField(
                choices=[
                    ("equipes", "11111"),
                    ("equipes", "22222"),
                    ("equipes", "33333"),
                    ("equipes", "44444"),
                    ("equipes", "55555"),
                    ("equipes", "66666"),
                    ("equipes", "77777"),
                    ("equipes", "88888"),
                    ("equipes", "99999"),
                    ("equipes", "00000"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pavimento",
            name="Equipe",
            field=models.CharField(
                choices=[
                    ("equipes", "11111"),
                    ("equipes", "22222"),
                    ("equipes", "33333"),
                    ("equipes", "44444"),
                    ("equipes", "55555"),
                    ("equipes", "66666"),
                    ("equipes", "77777"),
                    ("equipes", "88888"),
                    ("equipes", "99999"),
                    ("equipes", "00000"),
                ],
                max_length=255,
            ),
        ),
    ]
