# Generated by Django 4.1.1 on 2023-02-11 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('controle_pav', '0045_alter_esgoto_equipe_alter_pavimento_equipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateField(blank=True, null=True, verbose_name='data')),
                ('Qtd', models.BooleanField(default=False)),
                ('Equipe', models.CharField(choices=[('equipes', '11111'), ('equipes', '22222'), ('equipes', '33333'), ('equipes', '44444'), ('equipes', '55555'), ('equipes', '66666'), ('equipes', '77777'), ('equipes', '88888'), ('equipes', '99999'), ('equipes', '00000')], max_length=255)),
                ('Servico', models.CharField(choices=[('Operacional', 'Operacional'), ('Comercial', 'Comercial')], max_length=255)),
                ('Item', models.CharField(max_length=255)),
                ('Observacao', models.CharField(blank=True, max_length=255)),
                ('Devolucao', models.CharField(blank=True, max_length=255)),
                ('Localidade', models.TextField(choices=[('Salvador', 'Salvador'), ('Lauro', 'Lauro')], max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
