# Generated by Django 4.1.1 on 2023-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0046_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Executado',
            field=models.BooleanField(choices=[(True, 'Executado'), (False, 'Pendente')], default=False),
        ),
    ]
