# Generated by Django 4.1.1 on 2023-02-11 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0047_material_executado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Data',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
