# Generated by Django 4.1.1 on 2023-02-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0048_alter_material_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Executado',
            field=models.BooleanField(choices=[('Executado', 'Executado'), ('Pendente', 'Pendente')], default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='Qtd',
            field=models.CharField(max_length=1000),
        ),
    ]
