# Generated by Django 4.1.1 on 2023-02-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0049_alter_material_executado_alter_material_qtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Devolucao',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='Executado',
            field=models.BooleanField(choices=[('E', 'Executado'), ('P', 'Pendente')], default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='Localidade',
            field=models.TextField(choices=[('S', 'Salvador'), ('L', 'Lauro')], max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='Qtd',
            field=models.IntegerField(max_length=800),
        ),
        migrations.AlterField(
            model_name='material',
            name='Servico',
            field=models.CharField(choices=[('P', 'Operacional'), ('C', 'Comercial')], max_length=255),
        ),
    ]
