# Generated by Django 4.1.1 on 2023-02-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0050_alter_material_devolucao_alter_material_executado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Devolucao',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='Item',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='material',
            name='Qtd',
            field=models.IntegerField(),
        ),
    ]
