# Generated by Django 4.1.1 on 2023-02-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0056_alter_material_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='Na_reserva',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
