# Generated by Django 4.1.1 on 2023-02-12 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0057_material_na_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='Na_reserva',
            new_name='N_reserva',
        ),
    ]
