# Generated by Django 4.1.1 on 2023-02-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0058_rename_na_reserva_material_n_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='N_reserva',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
