# Generated by Django 4.1.1 on 2023-02-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0060_alter_material_n_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Devolucao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
