# Generated by Django 4.1.1 on 2023-02-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0061_alter_material_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Devolucao',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
