# Generated by Django 4.1.1 on 2023-02-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0063_lancamentos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lancamentos',
        ),
    ]
