# Generated by Django 4.1.1 on 2023-02-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0064_delete_lancamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Equipe',
            field=models.CharField(blank=True, choices=[('11111', '11111'), ('22222', '22222'), ('33333', '33333'), ('44444', '44444'), ('55555', '55555'), ('66666', '66666'), ('77777', '77777'), ('88888', '88888'), ('99999', '99999'), ('00000', '00000')], max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='Executado',
            field=models.BooleanField(blank=True, choices=[(True, 'Executado'), (False, 'Pendente')], default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='Servico',
            field=models.CharField(blank=True, choices=[('Operacional', 'Operacional'), ('Comercial', 'Comercial'), ('Unid. Tec', 'Unid. Tec')], max_length=255),
        ),
    ]
