# Generated by Django 4.1.1 on 2023-02-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0065_alter_material_equipe_alter_material_executado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Devolucao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
