# Generated by Django 4.1.1 on 2023-02-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0066_alter_material_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Data',
            field=models.DateField(blank=True, null=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='material',
            name='Devolucao',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
