# Generated by Django 4.1.1 on 2023-02-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_pav', '0067_alter_material_data_alter_material_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='N_reserva',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
